# Dockerfile: Defines container specifications to startup and run.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore
# Capacitação Redes - PV Intelbras

# Use networkboot DHCP image as base:
FROM ubuntu/bind9:9.18-22.04_edge
