# Main composition file for ZTP service using DHCP and TFTP servers: 
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore
# Capacitação Redes - PV Intelbras

version: '3.8'
services:
  # DHCP server service:
  dhcpserver:
    container_name: dhcpserver
    hostname: dhcpserver
    restart: always
    volumes:
      - "./serverDHCP/dhcpd.leases:/var/lib/dhcp/dhcpd.leases"
    #  - "./serverDHCP/dhcpd.conf:/etc/dhcp/dhcpd.conf"
    # Capabilities to add to the container to allow DHCP server to run:
    cap_add:
      - NET_ADMIN
    # Expose DHCP server ports:
    ports:
      - "67:67/udp"
      - "68:68/udp"
    # Map container build context to DHCPserver container:
    build:
      context: .
      dockerfile: ./serverDHCP/Dockerfile

  # TFTP server service:
  tftpserver:
    container_name: tftpserver
    hostname: tftpserver
    restart: always
    # Volume mount to share TFTP files:
    volumes:
      - "./config:/tftpshare"
    # Expose TFTP server port:
    ports:
      - "69:69/udp"
    # Map container build context to TFTPserver container:
    build:
      context: .
      dockerfile: ./serverTFTP/Dockerfile